# Generated by Django 5.1.1 on 2024-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FacturasMed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="monto",
            field=models.FloatField(verbose_name="Monto"),
        ),
    ]
