# Generated by Django 5.1.1 on 2024-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FacturasMed", "0002_alter_factura_monto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="fecha_vencimiento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Vencimiento"
            ),
        ),
    ]
